// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUpwPmpcrezTK-rLEEH6rlrFfb3OkqXg4',
    appId: '1:28130547258:web:c628f153ed0fa63daf8703',
    messagingSenderId: '28130547258',
    projectId: 'laundry-project-6c9d6',
    authDomain: 'laundry-project-6c9d6.firebaseapp.com',
    storageBucket: 'laundry-project-6c9d6.firebasestorage.app',
    measurementId: 'G-CFHZ3QRDTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl-ac8YRycoBH_-OS4dpN2tjRTnzHO1Pw',
    appId: '1:28130547258:android:b2a3db29f73ace99af8703',
    messagingSenderId: '28130547258',
    projectId: 'laundry-project-6c9d6',
    storageBucket: 'laundry-project-6c9d6.firebasestorage.app',
  );

}